swagger: '2.0'
info:
  description: This is a sample REST API
  version: 1.0.0
  title: Sample REST API
  contact:
    email: alessandro.resta@gmail.com
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
host: 127.0.0.1:8080
basePath: /v1
schemes:
  - http
paths:
  /ping:
    get:
      summary: ping endpoint
      tags:
        - ping
      operationId: ping
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              message:
                type: string
                example: pong
